import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Development is opt-in. A bare `node esbuild.config.mjs` therefore emits the production
// bundle, so a rebuild by anyone — a reviewer, CI, another machine — cannot silently
// produce a sourcemapped dev build that no longer matches the released artifact.
const dev = process.env.BUILD_ENV === "development";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  define: {
    __BUILD_ENV__: JSON.stringify(dev ? "development" : "production"),
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((name) => `node:${name}`),
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: dev ? "inline" : false,
  treeShaking: true,
  outfile: "main.js",
});

if (dev) {
  await context.watch();
} else {
  await context.rebuild();
  process.exit(0);
}
